### ISSUE TITLE
Error starting script

### ISSUE THREAD

**Issue by DylanVerstraete** [maxsam4/fork-off-substrate#81]
```
➜  fork-off-substrate git:(master) npm start

> fork-off-substrate@1.0.0 start /home/dylan/Projects/fork-off-substrate
> node index.js

We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
2022-02-16 18:34:11        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2022-02-16 18:34:11        API/INIT: Error: FATAL: Unable to initialize the API: Cannot convert undefined or null to object
    at ApiPromise.value (/home/dylan/Projects/fork-off-substrate/node_modules/@polkadot/api/base/Init.cjs:88:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Any idea what this means?

**Comment by DylanVerstraete** [comment]
Looks like I had to run the node with `--rpc-methods Unsafe` 

Upgrading the polkadot js client to version: [6.10.1](https://github.com/polkadot-js/api/releases/tag/v6.10.1) showed me the error.
